# listen and port changes require restart
listen: localhost
port: 5555
user: gwg
group: gwg
# minimum for each repo is url, (webhook) path and directory
repos:
  # required
  - url: git@github.com:ns/repo-1.git
    path: /ghwh
    directory: /path/to/clone/to
    #branch: masteraa
    # optional
    trigger: /path/to/trigger/file-a
    secret: superSecret-repo-1
    sshPrivKey: /path/to/priv/key
    sshPassPhrase: superPassPhrase-1
  - url: git@github.com:ns/repo-2.git
    path: /ghwha
    directory: /path/to/clone/to-2
    branch: master
    trigger: /path/to/trigger/file-2
    secret: superSecret-repo-2
    sshPrivKey: /path/to/priv/key-2
    sshPassPhrase: abc
