listen = "localhost"
port = 5555
retry_count = 10
retry_delay = 10
initialise = true
[logging]
format = "text"
output = "stdout"
level = "info"
timestamp = true
[[repos]]
url = "git@github.com:ns/repo-1.git"
path = "/gwg/repo-1"
directory = "/path/to/clone/to-1"
branch = "master"
remote = "origin"
trigger = "/path/to/trigger/file-1"
secret = "superSecret-repo-1"
sshPrivKey = "/path/to/priv/key-1"
sshPassPhrase = "pphrase-1"
[[repos]]
url = "git@github.com:ns/repo-2.git"
path = "/gwga"
directory = "/path/to/clone/to-2"
branch = "master"
remote = "origin"
trigger = "/path/to/trigger/file-2"
secret = "superSecret-repo-2"
sshPrivKey = "/path/to/priv/key-2"
sshPassPhrase = "abc"
